import type { HandleParams } from "./types";

export const defaultParams: HandleParams = {
  name: "Paddle brush",
  length: 118,
  buttRadius: 10.4,
  gripRadius: 12.6,
  neckRadius: 8.2,
  ovalRatio: 1.32,
  sides: 48,
  profile: "ergonomic",
  waist: 0.22,
  curveKind: "straight",
  bendAngle: 12,
  bendPosition: 0.62,
  twistTurns: 0,
  texture: "ribs",
  textureDepth: 0.35,
  textureScale: 1,
  pommel: "round",
  hangLoop: false,
  hangLoopRadius: 7.5,
  hangLoopTube: 2.4,
  attachment: "socket",
  attachDiameter: 12.2,
  attachDepth: 24,
  wallThickness: 2.6,
  clearance: 0.3,
  printFlat: 0.14,
};

export interface Preset {
  id: string;
  label: string;
  blurb: string;
  params: HandleParams;
}

export const PRESETS: Preset[] = [
  {
    id: "paddle",
    label: "Paddle brush",
    blurb: "Replacement handle for a paddle hairbrush. Round hole in the bottom for the remaining head stem.",
    params: { ...defaultParams },
  },
  {
    id: "round-brush",
    label: "Round brush",
    blurb: "Barrel grip for a round styling brush. Round hole in the bottom for the barrel stem.",
    params: {
      ...defaultParams,
      name: "Round brush",
      length: 102,
      buttRadius: 11,
      gripRadius: 13.5,
      neckRadius: 8,
      ovalRatio: 1,
      profile: "barrel",
      texture: "smooth",
      textureDepth: 0.2,
      attachDiameter: 11.4,
      attachDepth: 22,
      printFlat: 0.1,
    },
  },
  {
    id: "slim-tease",
    label: "Slim tease",
    blurb: "Long and thin — teasing or rattail-style handle. Round hole in the bottom for the pick stem.",
    params: {
      ...defaultParams,
      name: "Slim tease",
      length: 168,
      buttRadius: 6.2,
      gripRadius: 7.4,
      neckRadius: 4.4,
      ovalRatio: 1,
      profile: "straight",
      texture: "smooth",
      textureDepth: 0.15,
      pommel: "knob",
      attachment: "socket",
      attachDiameter: 4.8,
      attachDepth: 18,
      wallThickness: 2.2,
      printFlat: 0.08,
    },
  },
  {
    id: "comfort",
    label: "Comfort grip",
    blurb: "Oversized, dimpled grip — easier on tired or arthritic hands. Round hole in the bottom.",
    params: {
      ...defaultParams,
      name: "Comfort grip",
      length: 122,
      buttRadius: 17,
      gripRadius: 20,
      neckRadius: 10,
      ovalRatio: 1.12,
      profile: "barrel",
      texture: "dimple",
      textureDepth: 0.7,
      textureScale: 0.85,
      attachDiameter: 12.2,
      attachDepth: 26,
      wallThickness: 3.2,
      printFlat: 0.16,
    },
  },
  {
    id: "swirl",
    label: "Swirl wand",
    blurb: "Twisted, spiraled grip — decorative and tactile. Round hole in the bottom for a stem.",
    params: {
      ...defaultParams,
      name: "Swirl wand",
      length: 140,
      buttRadius: 9,
      gripRadius: 11.5,
      neckRadius: 7,
      ovalRatio: 1.18,
      sides: 36,
      profile: "barrel",
      curveKind: "gentle",
      bendAngle: 22,
      twistTurns: 1.6,
      texture: "spiral",
      textureDepth: 0.55,
      textureScale: 1.2,
      pommel: "knob",
      attachDiameter: 11,
      printFlat: 0.1,
    },
  },
  {
    id: "hook",
    label: "Hook grip",
    blurb: "Bent like a cane handle — hangs off a wrist or hook. Round hole in the bottom.",
    params: {
      ...defaultParams,
      name: "Hook grip",
      length: 148,
      buttRadius: 14,
      gripRadius: 16,
      neckRadius: 9,
      ovalRatio: 1.08,
      profile: "ergonomic",
      curveKind: "hook",
      bendAngle: 55,
      bendPosition: 0.72,
      texture: "flutes",
      textureDepth: 0.45,
      hangLoop: true,
      attachDiameter: 12,
      printFlat: 0,
    },
  },
  {
    id: "screwdriver",
    label: "Driver",
    blurb: "Faceted, knurled tool handle with a round hole in the bottom for a shaft.",
    params: {
      ...defaultParams,
      name: "Driver",
      length: 98,
      buttRadius: 14,
      gripRadius: 15.5,
      neckRadius: 8,
      ovalRatio: 1,
      sides: 8,
      profile: "flare",
      waist: 0.1,
      curveKind: "straight",
      twistTurns: 0,
      texture: "knurl",
      textureDepth: 0.55,
      textureScale: 1.15,
      pommel: "flare",
      hangLoop: false,
      attachment: "socket",
      attachDiameter: 6.2,
      attachDepth: 22,
      wallThickness: 3.2,
      printFlat: 0.12,
    },
  },
  {
    id: "hex-rasp",
    label: "Hex rasp",
    blurb: "Six-sided with diamond knurl — file, chisel, or awl. Round hole in the bottom.",
    params: {
      ...defaultParams,
      name: "Hex rasp",
      length: 110,
      buttRadius: 13,
      gripRadius: 14.2,
      neckRadius: 7.5,
      ovalRatio: 1,
      sides: 6,
      profile: "straight",
      texture: "diamond",
      textureDepth: 0.5,
      textureScale: 1,
      pommel: "flat",
      attachment: "socket",
      attachDiameter: 8,
      attachDepth: 20,
      wallThickness: 3,
      printFlat: 0,
    },
  },
  {
    id: "kitchen",
    label: "Kitchen",
    blurb: "Flat oval spatula / spoon handle. Round hole in the bottom for a head stem.",
    params: {
      ...defaultParams,
      name: "Kitchen",
      length: 132,
      buttRadius: 9,
      gripRadius: 11,
      neckRadius: 7,
      ovalRatio: 1.7,
      sides: 48,
      profile: "waisted",
      waist: 0.28,
      texture: "rings",
      textureDepth: 0.3,
      textureScale: 0.8,
      pommel: "round",
      attachment: "socket",
      attachDiameter: 8.4,
      attachDepth: 26,
      wallThickness: 2.8,
      printFlat: 0.22,
    },
  },
  {
    id: "toothbrush",
    label: "Toothbrush",
    blurb: "Slim, slightly curved, with a round hole in the bottom for a brush head stem.",
    params: {
      ...defaultParams,
      name: "Toothbrush",
      length: 150,
      buttRadius: 6.8,
      gripRadius: 8.2,
      neckRadius: 4.6,
      ovalRatio: 1.15,
      profile: "ergonomic",
      curveKind: "gentle",
      bendAngle: 14,
      texture: "ribs",
      textureDepth: 0.25,
      textureScale: 1.4,
      pommel: "round",
      attachment: "socket",
      attachDiameter: 3.6,
      attachDepth: 14,
      wallThickness: 2.2,
      printFlat: 0.18,
    },
  },
];

export function presetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
